LABELS = ['LAYING', 'SITTING', 'STANDING', 
		'WALKING', 'WALKING_DOWNSTAIRS','WALKING_UPSTAIRS']
SECRET_KEY = '40dT0pPSlDqfS8HH0L1peqPVkHo0kAuCYOfptKq2'
ACCESS_KEY = 'IUFU7Qjcv7diYlHckyYo'
BUCKET_NAME = 'bucket-test'